### ISSUE TITLE
[Question / Feature Request] Using Firestation to migrate data structure

### ISSUE THREAD

**Issue by willbattel** [JoeRoddy/firestation#1]
Hello, thanks for making this cool tool!

I was wondering if I could get it to do this task for me.

I used to store location pairs for my users like this:
```
coordinate:
├─ latitude: [float]
└─ longitude: [float]
```
but now I'm recording new locations like this:
```
location:
└─ coordinates:
   ├─ latitude: [float]
   └─ longitude: [float]
```

and I was wondering if I could use Firestation to give all existing users, who still have the old `coordinate` data structure, the `location` object data using their existing `coordinate` data. Some sort of `update` query that simply set `location.coordinates.latitude` to `coordinate.latitude` and `location.coordinates.longitude` to `coordinate.longitude`.

Is this possible?
Thanks!

**Comment by JoeRoddy** [comment]
Not yet, but I've had this same scenario come up for me a bit too.  I'll try to think of a way to implement this.

What would you expect the actual query to look like?

[According to this](https://stackoverflow.com/questions/4328814/using-sql-how-do-i-update-rows-using-their-own-values), the way it would look in actual SQL would be like so:
update users set location.coordinates.latitude = coordinate.latitude;

Then for each item, the coordinate.latitude on the right would refer to that item's coordinate.latitude.  At the moment I think it would actually just set every prop equal to the string "coordinate.latitude", but I can take a look at this.  It's a good idea.

**Comment by JoeRoddy** [comment]
https://www.youtube.com/watch?v=Mu-0eI-LIRI&feature=youtu.be

Check this out and let me know if it solves your problem.  If you want to test it out, you'll have to clone the repo and then run 

`
npm i 
npm run dev
`

Won't be available in the app from the website for a while.  Still haven't set up auto-updates either :/

**Comment by wbattel4607** [comment]
Video looked good! I'll try it out this week and let you know. Thanks!
