### ISSUE TITLE
instructions on how to add private key

### ISSUE THREAD

**Issue by inglesuniversal** [JoeRoddy/firestation#11]
Hello: I added my private key.json file obtained from firebase panel / adminsdk / generate key / export key => mykey.json file

But, when trying to read any data or export database I get NULL

If I am able to see the data on my Firebase Panel... What is is that I am missing to fix this issue that I get no data.

Regards

-----------

UPDATE:

I just notice that NO data was read since the setup I have is for Cloud Firestore...  and NOT Realtime Database.... You don't support that right now? Is there any advantage of using the Realtime Database vs the Cloud Firestore? Thanks.

**Comment by JoeRoddy** [comment]
Hi @inglesuniversal !!  Firestore is a work in progress on the [projectRevamp](https://github.com/JoeRoddy/firestation/tree/projectRevamp) branch.  You would have to get it running locally to try it out.

`npm install`

`npm start`

If you have any problems with it you can post it in the [firestore issue](url).

Good luck!
