### ISSUE TITLE
How to filter query in Firestation by using Firebase Auth UID

### ISSUE THREAD

**Issue by SilveradoGiant** [JoeRoddy/firestation#13]
Hopefully somebody can help me, I’m trying to query the Firebase DB with Firestation but I would like to get the value for a specific user id. This user id is the one generated by the Firebase Authentication. I can’t find an example on how to do it. Here is what I’m trying to do:

select * from Users where Users.UID = ‘XRr2tX8OhvMCOmwLsqZoVIHiKUG2’;

The UID is a node below the Users table.

![screen shot 2019-02-28 at 11 53 11 am](https://user-images.githubusercontent.com/48099962/53584423-e9136000-3b59-11e9-850c-8f021c4632d5.png)

**Comment by lephukhanhhuy** [comment]
Please try:
select * from Users.XRr2tX8OhvMCOmwLsqZoVIHiKUG2

**Comment by JoeRoddy** [comment]
thanks for the response @lephukhanhhuy !!
