### ISSUE TITLE
Firestation not working on windows 7

### ISSUE THREAD

**Issue by jesusplayer** [JoeRoddy/firestation#14]
Hello, thanks for this useful tool. But after launching it on windows 7, it doesn't query data.
I need help, Please. (firestation v1.2.0)
![Capture](https://user-images.githubusercontent.com/11212084/58083466-f2d4be80-7bb0-11e9-9f64-ce8d943fb485.PNG)

**Comment by JoeRoddy** [comment]
Sorry @jesusplayer , just noticed this.  I haven't tried launching it on windows in a while, but I would expect the downloadable version from the website to work.  

I'll try to launch it today.  To me it looks like it's not throwing an error, but just returning 0 results.  So it might just be an issue with the db connection or maybe you're trying to fetch results from Firestore, while this is querying the realtime db.

**Comment by jesusplayer** [comment]
Thanks a lot @JoeRoddy have you lunched it? what are the results?

**Comment by JoeRoddy** [comment]
Just tried it @jesusplayer and it seems to be okay.  Are you sure that that database is using the realtime DB and not firestore?  Are you sure that there are users?

If you're still getting 0 results, you can run the 'Example Insert' on the left pane, execute and commit.  Then, run the select statement again.  You should see the newly inserted records when you run the select.

**Comment by JoeRoddy** [comment]
Importantly, Firestation is just checking the 'users' collection in the database.  When you create users with firebase.auth(), it doesn't actually create a record in the database itself, but in a separate authentication system.  So unless you have data in a 'users' collection in the database, you won't see results.

**Comment by jesusplayer** [comment]
Thank you @JoeRoddy for your clarifications. I think it is because i use firestaore. So it mean that i cannot use **Firestation** with firestore ?

**Comment by JoeRoddy** [comment]
Not in the current version, but there's a firestore version currently being worked on.
