### ISSUE TITLE
Set up question

### ISSUE THREAD

**Issue by mjordan-23** [JoeRoddy/firestation#28]
i have installed firestation and want to configure the connection
where could i find the exact DB name and New Key combination which is required ?
are they somewhere in these ?
"type": 
  "project_id": 
  "private_key_id":
  "private_key":
  "client_email": 
  "client_id": 
  "auth_uri": 
  "token_uri":
  "auth_provider_x509_cert_url": 
  "client_x509_cert_url": 

thanks in advance

**Comment by JoeRoddy** [comment]
Hey @mjordan-23 ,

You can name the database anything you want, that will just be for you to choose the database later within Firestation.

During setup, the app will ask you to upload a service account json file, which can be exported from the Firebase console.

To create the file:
https://console.firebase.google.com/u/0/project/_/settings/serviceaccounts/adminsdk

More info:
https://firebase.google.com/docs/admin/setup

**Comment by mjordan-23** [comment]
i dont know what i am missing here... in DB Config - i can name the DB anything -got that.
I want to enter the "Current Service Account: " so i click <New Key> file manager opens and i have to select a *.json file... What file do i select?  where do i find it ?  
When i go to my DB in Firebase .. I click on the setting gear ... select "Project settings" ..and i see a heading "Service accounts" should i be doing something here?
thanks, again, in advance

**Comment by JoeRoddy** [comment]
@mjordan-23 

go to Service Accounts and then click 'Generate new private key'

![image](https://user-images.githubusercontent.com/16690442/68450475-3a7bf080-01b9-11ea-9430-e8600b37ecc0.png)
