### ISSUE TITLE
Firestore support for WHERE id =

### ISSUE THREAD

**Issue by devpascoe** [JoeRoddy/firestation#8]
I do not believe currently there is support for a select * from collectionName where id = '12345678'
Am i correct or just not looking hard enough at the docs?

**Comment by JoeRoddy** [comment]
That one should definitely work. Is there any error output in the console?

**Comment by JoeRoddy** [comment]
https://docs.firestation.io/#where-clauses-filtering-data

But I'm guessing you're hitting another random bug.

**Comment by JoeRoddy** [comment]
Ohhhhhhhhhhhhhh, I see.

You want:

`select * from collectionName.id`

Yeah, you can only filter/query data that is actually on the document. 

Let me know if that^ works

**Comment by devpascoe** [comment]
bingo! thanks
